### ISSUE TITLE
请问启动一直报错是怎么回事

### ISSUE THREAD

**Issue by lijianru** [superman66/react-test-demo#5]
![image](https://user-images.githubusercontent.com/28643081/50276818-d4da2500-047d-11e9-8261-51560181081b.png)

**Comment by superman66** [comment]
你是 mac 还是 windows？如果是 windows，加个 cross-env 试试

**Comment by lijianru** [comment]
已解决！先 `npm install cross-env` 然后再 修改运行脚本为`"dev": "cross-env NODE_ENV=development webpack-dev-server  --inline --progress --colors --port 3000 --host 0.0.0.0 --devtool source-map",`
